WebApplication1/Controllers/TacoShopController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TacoShop.Domain.Interfaces.Service;
using TacoShop.Domain.Model;

namespace FrontShop.Web.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class TacoShopController : Controller
    {
        private readonly IBuyService _buyService;
       public TacoShopController(IBuyService buyService)
        {
            _buyService = buyService;
        }

        [HttpGet("SearchForMenu")]
        public async Task<ActionResult<IEnumerable<TacoRestaurant>>> SearchForMenu(string searchString)
        {
            var tacoMenu = await _buyService.GetAllAvailableSortedSearchedMenu(searchString);
            return View(tacoMenu);
        }

        [HttpPost("PlaceOrder")]
        public ActionResult PlaceOrder()
        {
            return View();
        }
    }
}

WebApplication1/Views/Shop/Shop.cshtml
@model TacoShop.Domain.Model.TacoRestaurant;

@using (Html.BeginForm("SearchForMenu", "TacoShop", FormMethod.Get))
{
    <p>
        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { style = "width:50%" })
        <input type="submit" value="Search" />
    </p>
}

WebApplication1/Views/TacoShop/SearchForMenu.cshtml
@model IEnumerable<TacoShop.Domain.Model.TacoRestaurant>

    @using (Html.BeginForm("PlaceOrder", "TacoShop", FormMethod.Get))
    {
        @if (Model != null)
        {

            foreach (var item in Model)
            {
                <img src="@Url.Content(item.LogoPath)" alt="IMAGES" />
                @Html.LabelFor(Model => item.Name, item.Name) @Html.LabelFor(m => item.Suburb, " - " + item.Suburb) @Html.LabelFor(m => item.Rank, " ranked #" + item.Rank + " overall")
                <br />
                foreach (var items in item.Categories)
                {
                    foreach (var menuItems in items.MenuItems)
                    {

                        @Html.CheckBoxFor(m => menuItems.Checked, new { @onclick = "clicked()" })
                        @Html.HiddenFor(m => menuItems.Id)
                        @Html.LabelFor(m => menuItems.name, menuItems.name) @Html.LabelFor(m => menuItems.Price, " - R" + menuItems.Price.ToString())
                        <br />
                    }
                    <br />
                }
                <br />

            }
            <p>
                <input type="submit" value="Order" />
            </p>
        }
    }


}